field.value.extra_secret_code:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.formatter.settings.extra_secret_code_base:
  type: mapping
  label: ExtraSecretCodeFormatter formatter settings
  mapping:
    foo:
      type: string
      label: Foo

field.widget.settings.extra_secret_code_base:
  type: mapping
  label: ExtraSecretCodeWidget widget settings
  mapping:
    foo:
      type: string
      label: Foo
